services:
  - type: web
    name: pogoda34-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: RENDER_URL
        sync: false
    autoDeploy: true
