name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Раз в 10 минут (хватит, чтобы не уснуть)
  workflow_dispatch:        # Можно запустить вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -I https://pogoda34-bot-1pogoda34-bot.onrender.com/
          echo "Pinged pogoda34-bot-1pogoda34-bot.onrender.com"
